[project]
name = "molecule-renumber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "pyqt6>=6.9.1",
    "pyqt6-webengine>=6.9.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.16.0",
]
